### PR TITLE
Update CLI helpdoc formatting to allow indentation in code

### PR DESCRIPTION
**Pull request by sugatoray**
Use `textwrap.dedent()` to allow indented cli-helpdoc in `__main__.py` file. The indentation increases readability, while `textwrap.dedent` helps maintain the same functionality without breaking code.

image

### CODE REVIEW

**Comment by sugatoray** [comment]
> @sugatoray please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by sugatoray** [comment]
cc: @gagb

**Comment by gagb** [comment]
can you please run precommit?

**Comment by gagb** [comment]
Can also please share a screenshot of how different the output of `markitdown --help` looks before and after?

**Comment by sugatoray** [comment]
Hi @gagb,

1. I have updated the code post running pre-commit.

2. Here is the screenshot of `markitdown --help` 
   - **`AFTER`** the update: (please refer to the version number printed right after)
     > image

   - **`BEFORE`** the update:
     > `TBD...`

**Comment by sugatoray** [comment]
@gagb: I have shared the screenshots. Thank you.

**Comment by gagb** [comment]
I am unfortunately having a hard time seeing a difference? What did I miss? @afourney

**Comment by sugatoray** [comment]
> I am unfortunately having a hard time seeing a difference? What did I miss? @afourney

There should not be any difference b/w the helpdoc before and after the change. The image at the top shows what changes in the code. And my screenshots show that the cli-help is still unchanged.

:bulb: There was a button to update the branch with regard to the `main` branch to avoid any conflicts later on. I clicked on it. And that's why it requires now for another `pre-commit` and `tests` validation.

image

**Comment by gagb** [comment]
My bad, I now understand the `dedent` feature. Pretty cool!

**Comment by sugatoray** [comment]
> My bad, I now understand the `dedent` feature. Pretty cool!

@gagb No issues. Perhaps the title of the PR was a bit confusing. 

The branch was not ready to merge despite the checks being passed. So, I updated the branch. If you could let the checks re-run, and then merge it, that will be helpful.

Please let me know if there is anything else necessary from my end. Thank you.

**Comment by sugatoray** [comment]
@gagb, @afourney: Thank you for reviewing and merging.

**Comment by gagb** [comment]
> @gagb, @afourney: Thank you for reviewing and merging.

Thank YOU for contributing!

**Pull request merged**
