### PR TITLE
Safeguard against path traversal for ZipConverter

### PR DESCRIPTION
**Pull request by finchy**
fix: prevent path traversal vulnerabilities in ZipConverter

Added a secure check for path traversal vulnerabilities in the ZipConverter class. Now validates extracted file paths using `os.path.commonprefix` to ensure all files remain within the intended extraction directory. Raises a `ValueError` if a path traversal attempt is detected.

- Normalized file paths using `os.path.normpath`.
- Added specific exception handling for `zipfile.BadZipFile` and traversal errors.
- Ensured cleanup of extracted files after processing when `cleanup_extracted` is enabled.

### CODE REVIEW

**Comment by finchy** [comment]
@microsoft-github-policy-service agree [company="{ThreatSTOP}"]

**Comment by finchy** [comment]
@microsoft-github-policy-service agree

**Comment by finchy** [comment]
@microsoft-github-policy-service agree company="ThreatSTOP"

**Comment by gagb** [comment]
@Josh-XT FYI

**Comment by Josh-XT** [comment]
> @Josh-XT FYI, can you please take a look?

Looks like a good improvement to me!

**Comment by afourney** [comment]
Zip this issue is what keeps me up at night re: zip files. (The problem is worse with tar files, which we do not support). 

PR, looks reasonable to me, but I want to get another few opinions. We might even consider not excluding zip support by default -- making it optional.

**Review by Josh-XT — APPROVED** [review]

**Comment by afourney** [comment]
Thinking on this more, I believe it is possible to open a byte stream for a file in the Zip, without requiring that we decompress the whole archive. We could in theory enumerate supported files, and one by one write them to a tmp file on disk (with a safe name and permissions), and convert the, and clean them up.

In any case, I'll merge this PR now (as it is strictly better), and we can revisit in a future PR.

**Review by afourney — COMMENTED** [review]
Approved and merged. See discussion.

**Pull request merged**
