### PR TITLE
Update _markitdown.py

### PR DESCRIPTION
**Pull request by GH0STH4CKER**
Updated code to install modules when the try catch block finds a ModuleNotFOundError

### CODE REVIEW

**Comment by GH0STH4CKER** [comment]
> @microsoft-github-policy-service agree

**Comment by GH0STH4CKER** [comment]
> @GH0STH4CKER please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement



> @GH0STH4CKER please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by l-lumin** [comment]
why do this when have pyproject.toml? I think It's unusual behavior.

**Comment by gagb** [comment]
Thanks for the contribution. Same question as above.

**Comment by gagb** [comment]
Thanks for the PR. @afourney and I discussed. In the new year we will examine how to best organize the growing list of dependencies so we are not ready to accept this PR/approach.

**Comment by GH0STH4CKER** [comment]
> why do this when have pyproject.toml? I think It's unusual behavior.

Thanks for the feedback! The intent behind this change was to add runtime flexibility in case dependencies aren’t installed in certain environments, even though they're listed in pyproject.toml. This was meant to prevent runtime errors and make the script more self-sufficient, especially in cases where the environment might be missing certain packages. However, I totally get the concern about introducing unexpected behavior. Happy to refine this if it’s not in line with the project's standard approach!

**Comment by GH0STH4CKER** [comment]
> Thanks for the PR. @afourney and I discussed. In the new year we will examine how to best organize the growing list of dependencies so we are not ready to accept this PR/approach.

Why did you **closed** it ?

**Pull request closed without merging**
