### PR TITLE
added installation instructions

### LINKED ISSUE #69: Add conda installation instructions
Conda makes dependency handling much simpler, and it would be good to add the recipe/instructions.

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes #69

### CODE REVIEW

**Comment by gagb** [comment]
@sarthakpati -- we are not publishing to conda. Who is publishing this package?

**Comment by rudrakshkarpe** [comment]
> @sarthakpati -- we are not publishing to conda. Who is publishing this package?

True, when I try to install the it says there's no availability of package. @gagb Any plans on publishing it to conda or conda-forge? 

Image

**Comment by sarthakpati** [comment]
Ah, I understand! I have updated the installation instructions to point to the correct channel.

**Comment by gagb** [comment]
> > @sarthakpati -- we are not publishing to conda. Who is publishing this package?
> 
> True, when I try to install the it says there's no availability of package. @gagb Any plans on publishing it to conda or conda-forge?
> 
> Image

We haven't published the conda package. @sarthakpati are you?

**Comment by gagb** [comment]
Hi @sarthakpati, @rudrakshkarpe,

I discussed with @afourney  and @jackgerrits.
Thanks for the work on the conda recipe. For now, we won’t be able to accept this PR. The package is already available on PyPI. You should be able to install it within a conda env.

**Comment by sarthakpati** [comment]
> We haven't published the conda package. @sarthakpati are you?

@johnhany97 did the initial publish, and I am a maintainer of the conda recipe.

**Pull request closed without merging**
